### ISSUE TITLE
Run on file save?

### ISSUE THREAD

**Issue by OoLunar** [gaoshan0621/vscode-csharp-format-usings#4]
I'd like to sort my using statements when I format the file (which runs when the file is saved). Can there be a config setting to do this automatically?

**Comment by skplunkerin** [comment]
I'm searching for this as well, even if it's something I need to configure myself in my `settings.json` file.

**Comment by OoLunar** [comment]
There's an .editorconfig option to do just this, I think:
```ini
# Organize usings
dotnet_sort_system_directives_first = true:error
```
